# Generated by Django 4.2.19 on 2025-02-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_pics',
        ),
    ]
